version: '3.8'
services:
  db:
    image: postgres:15
    container_name: portfolio_db
    restart: always
    environment:
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: portfolio_pass
      POSTGRES_DB: portfolio_db
    ports:
      - "5435:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
